export const landingContent = {
  nav: {
    logo: { url: "/images/logo.png", alt: "شعار كابتن فرحان" },
    links: [
      { label: "الرئيسية", href: "#home" },
      { label: "الرحلة", href: "#method" },
      { label: "النتائج", href: "#transformations" },
      { label: "الباقات", href: "#pricing" },
    ],
    ctaText: "ابدأ رحلتك",
    ctaMessage: "مرحبًا كابتن أحمد، أريد معرفة تفاصيل التدريب أونلاين.",
    whatsappNumber: "201028720683",
  },
  coach: { name: "أحمد فرحان", role: "مدرب لياقة وتغذية أونلاين" },
  hero: {
    eyebrow: "تدريب أونلاين مصمم ليك",
    headline: "ابني جسمك. قوّي التزامك. وخلّي النتيجة تتكلم.",
    subheadline: "خطة تمرين وتغذية مناسبة لهدفك، مع متابعة حقيقية تساعدك تكمل حتى في الأيام الصعبة.",
    heroPhotoUrl: "/images/coach/coach-hero.jpg",
    heroPhotoAlt: "أحمد فرحان داخل الجيم",
    ctaText: "كلّم الكابتن",
    ctaMessage: "مرحبًا كابتن أحمد، أريد أن أبدأ خطة تدريب مناسبة لهدفي.",
    whatsappNumber: "201028720683",
    stats: [
      { value: "01", label: "خطة على مقاسك" },
      { value: "24/7", label: "متابعة ودعم" },
      { value: "100%", label: "التزام بالنتيجة" },
    ],
  },
  about: {
    eyebrow: "وراء الخطة",
    title: "التغيير الحقيقي يبدأ بخطة تقدر تعيش بيها.",
    description: "مش هديك جدول وخلاص. هنفهم هدفك، وقتك، مستواك، والأكل اللي يناسب يومك، وبعدها نبني نظام واضح تقدر تلتزم بيه وتطوره خطوة بخطوة.",
    aboutPhotoUrl: "/images/coach/coach-about.jpg",
    aboutPhotoAlt: "أحمد فرحان في الجيم",
    credentials: [
      "خبرة 10 سنوات في التدريب واللياقة",
      "تدريب مخصص حسب هدفك ومستواك",
      "تعديلات مستمرة بناءً على تقدمك",
      "إرشادات تغذية عملية تناسب حياتك",
    ],
  },
  method: {
    eyebrow: "المنهج",
    title: "ثلاث خطوات تفصل بينك وبين النسخة الأقوى منك.",
    steps: [
      { number: "01", title: "نفهم هدفك", text: "نحدد نقطة البداية والهدف والوقت المتاح ليك." },
      { number: "02", title: "نبني خطتك", text: "تمرين وتغذية مصممين على ظروفك، مش جدول محفوظ." },
      { number: "03", title: "نتابع ونطوّر", text: "نراجع تقدمك ونعدّل الخطة عشان تفضل ماشي لقدام." },
    ],
  },
  pricing: {
    eyebrow: "ابدأ من مكانك",
    title: "اختار مدة المتابعة المناسبة ليك",
    subtitle: "نفس المتابعة الكاملة، والاختلاف في مدة التزامك بالخطة.",
    whatsappNumber: "201028720683",
    whatsappMessage: "مرحبًا كابتن أحمد، أريد الاشتراك في باقة",
    note: "باقة الـ3 شهور هي الأفضل للاستمرارية وتحقيق نتيجة واضحة.",
    plans: [
      { name: "الباقة الشهرية", price: "١٥٠٠ جنيه", duration: "متابعة لمدة شهر كامل", features: ["نظام غذائي متكامل يناسب وقتك وجيبك", "جدول تمرين مخصص ليك بالفيديوهات التوضيحية", "متابعة شخصية مع الكوتش باستمرار", "خطة مكملات اختيارية", "تعديل الخطة حسب الاحتياج"], ctaText: "اشترك شهريًا", highlighted: false },
      { name: "باقة 3 شهور", price: "٣٥٠٠ جنيه", duration: "متابعة كاملة لمدة 3 شهور", features: ["نظام غذائي متكامل يناسب وقتك وجيبك", "جدول تمرين مخصص ليك بالفيديوهات التوضيحية", "متابعة شخصية مع الكوتش باستمرار", "خطة مكملات اختيارية", "تعديل الخطة حسب الاحتياج"], ctaText: "ابدأ 3 شهور", highlighted: true },
    ],
  },
  transformations: {
    eyebrow: "النتيجة بتبان",
    title: "رحلات حقيقية. شغل حقيقي.",
    subtitle: "كل تغيير بدأ بخطوة صغيرة والتزام مستمر.",
    // اكتب قصة كل عميل داخل story وسيتم عرضها عند الضغط على الصورة.
    items: [
      { src: "/images/transformations/transformation-1.jpg", alt: "نتيجة عميل 1", story: "" },
      { src: "/images/transformations/transformation-2.jpg", alt: "نتيجة عميل 2", story: "" },
      { src: "/images/transformations/transformation-3.jpg", alt: "نتيجة عميل 3", story: "" },
      { src: "/images/transformations/transformation-4.jpg", alt: "نتيجة عميل 4", story: "" },
      { src: "/images/transformations/transformation-5.jpg", alt: "نتيجة عميل 5", story: "" },
      { src: "/images/transformations/transformation-6.jpg", alt: "نتيجة عميل 6", story: "" },
      { src: "/images/transformations/transformation-7.jpg", alt: "نتيجة عميل 7", story: "" },
      { src: "/images/transformations/transformation-8.jpg", alt: "نتيجة عميل 8", story: "" },
    ],
  },
  faq: {
    eyebrow: "أسئلة سريعة",
    title: "قبل ما تبدأ، خلّي الصورة واضحة",
    items: [
      { question: "هل التدريب أونلاين مناسب للمبتدئين؟", answer: "أيوه. الخطة بتبدأ من مستواك الحالي، وبتتطور مع تقدمك سواء بتتمرن في جيم أو في البيت." },
      { question: "هل الخطة تشمل التغذية؟", answer: "الباقات المتكاملة تشمل توجيه تغذية عملي، مع كميات وتعديلات تناسب هدفك وروتينك." },
      { question: "كيف تتم المتابعة؟", answer: "من خلال لوحة خاصة ليك وواتساب، مع مراجعة تقدمك وتحديث الخطة عند الحاجة." },
    ],
  },
  contact: {
    eyebrow: "جاهز تبدأ؟",
    title: "ابعت هدفك ونبدأ من النقطة الصح",
    description: "سيب بياناتك، أو كلّمنا مباشرة على واتساب. هنرد عليك ونفهم هدفك قبل ما نرشحلك أي باقة.",
    nameLabel: "الاسم",
    phoneLabel: "رقم واتساب",
    messageLabel: "هدفك من التدريب",
    namePlaceholder: "اكتب اسمك",
    phonePlaceholder: "01xxxxxxxxx",
    messagePlaceholder: "عايز تخس، تبني عضل، ولا تحسن لياقتك؟",
    submitText: "إرسال الطلب",
    successText: "وصلت رسالتك بنجاح. هنتواصل معاك قريبًا.",
    whatsappText: "تواصل على واتساب",
    whatsappNumber: "201028720683",
    whatsappMessage: "مرحبًا كابتن أحمد، أريد الاستفسار عن التدريب أونلاين.",
  },
  footer: {
    logo: { url: "/images/logo.png", alt: "شعار كابتن فرحان" },
    tagline: "خطة أوضح. التزام أقوى. نتيجة حقيقية.",
    quickLinks: [{ label: "الرئيسية", href: "#home" }, { label: "النتائج", href: "#transformations" }, { label: "تواصل معنا", href: "#contact" }],
    social: { Instagram: "https://www.instagram.com/ahmed__farhan_/", Facebook: "[placeholder]", TikTok: "[placeholder]", WhatsApp: "https://wa.me/201028720683" },
    copyrightText: "© 2026 أحمد فرحان. جميع الحقوق محفوظة.",
  },
} as const;

export type LandingContent = typeof landingContent;
